### ISSUE TITLE
num_train_steps是一块卡还是多块卡的step？

### ISSUE THREAD

**Issue by zhengyima** [guotong1988/BERT-GPU#26]
因为观察到单卡的steps/sec会比多卡还要快？所以疑惑是不是对num_train_steps理解有误。

举例来说，如果num_train_steps设为1000，有4块卡，那实际总共是跑了1000 steps还是4000 steps呢？

**Comment by guotong1988** [comment]
4000

**Comment by guotong1988** [comment]
For `HierarchicalCopyAllReduce` `MirroredStrategy`, `global_step/sec` shows the sum of multi gpus' steps.

**Comment by rxc205** [comment]
> 4000

所以，按照这个意思，num_train_steps是对应每一张卡的步长，我要想减少训练时间（其余参数不变的情况下），那我降低num_train_steps就行吗？

**Comment by guotong1988** [comment]
@rxc205 提升learning rate，见README：

![image](https://user-images.githubusercontent.com/4702353/127252180-29562407-144c-437f-a1e0-a3fd22588da6.png)
