### ISSUE TITLE
这个多GPU到底能加速训练吗？

### ISSUE THREAD

**Issue by rxc205** [guotong1988/BERT-GPU#30]
1.我看了一下closed issues , 我被绕晕了。我现在正在使用3张卡跑这个代码，我算了一下不能减少训练时间，和单卡一样也要运行11小时左右。
![image](https://user-images.githubusercontent.com/21190097/127136577-eacc304a-09db-4e5e-bdaa-21e477477ed6.png)
这里多GPU训练是说能够加速loss的下降吗？我在其他场景使用多GPU都是可以减少训练时间的

2.这个num_train_steps=10000，是说3张卡一共训练10000步长还是单张卡的step呢？

**Comment by guotong1988** [comment]
加速与否是learning-rate决定的

**Comment by guotong1988** [comment]
num_train_steps=10000，3卡，实际30000

**Comment by guotong1988** [comment]
README有写

![image](https://user-images.githubusercontent.com/4702353/127252117-9c90897b-c3b4-42cd-9818-cefcf06be410.png)

**Comment by rxc205** [comment]
> README有写
> 
> ![image](https://user-images.githubusercontent.com/4702353/127252117-9c90897b-c3b4-42cd-9818-cefcf06be410.png)

请问这里one data LR fixed和one batch LR fixed分别是什么意思呢？
我有一个疑问，我相同的100条数据，在3张卡跑num_train_steps=100，你的意思是我这一百条数据分别在每张卡跑100step吗？这样同等数据下3*100=300steps？是这个意思吗？

**Comment by guotong1988** [comment]
300个数据

**Comment by guotong1988** [comment]
字面意思

**Comment by rxc205** [comment]
> 300条数据

我的数据总量只有100条，你说的300条数据是什么意思？

**Comment by guotong1988** [comment]
相当于300

**Comment by rxc205** [comment]
> 相当于300

行，麻烦再问一个问题：
你这个多GPU和普通的不太一样啊。100条数据不是给3张卡一起处理，而是扩成300条给3张卡处理。
如果通过增大LR来减少训练时间的话，那域训练和微调时候性能是不是必然会下降啊？按照你这个代码的逻辑

**Comment by guotong1988** [comment]
没人逼你用我这个

**Comment by guotong1988** [comment]
![image](https://user-images.githubusercontent.com/4702353/127271505-c9e945f7-45a0-4826-a959-055b812345af.png)

**Comment by rxc205** [comment]
> 没人逼你用我这个

抱歉，是我言语有些激烈了。但是这问题确实想知道您的一些见解
100条数据3张卡，扩成300条给3张卡处理。
如果通过增大LR来减少训练时间的话，那域训练和微调时候性能是不是必然会下降啊？不知道我哪里有误解

**Comment by guotong1988** [comment]
learning rate 变大是 batch size 变大带来的，每个data产生的反向传播梯度不变，所以效果不下降
