### ISSUE TITLE
train 10W steps结束后，do_eva阶段出现错误

### ISSUE THREAD

**Issue by rxc205** [guotong1988/BERT-GPU#31]
![image](https://user-images.githubusercontent.com/21190097/127258299-04877cfe-939e-410f-bda3-eed674e740a6.png)

![image](https://user-images.githubusercontent.com/21190097/127258242-f20aea2a-4507-437b-939e-5f4b40ed5d8b.png)

do_train完成后，开启do_eval的时候，出现这个错误

**Comment by guotong1988** [comment]
eval 代码没写完

**Comment by rxc205** [comment]
> eval 代码没写完

OK，我的train loss 最终降到了4.几，请问一下你们在train的时候loss一般是多少，我这边使用的数据量是70W条Max length=128的文本数据

**Comment by guotong1988** [comment]
README.md
