### ISSUE TITLE
an error like this : Segmentation fault (core dumped),Is the configuration wrong?

### ISSUE THREAD

**Issue by Nanamumuhan** [guotong1988/BERT-GPU#33]
![image](https://user-images.githubusercontent.com/41236260/183324513-47ff574e-e90c-4485-8714-445147d77927.png)

**Comment by Nanamumuhan** [comment]
tensorflow,tensorflow-gpu  = 1.14.0        
NVIDIA-SMI 440.118.02   Driver Version: 440.118.02   CUDA Version: 10.2

**Comment by guotong1988** [comment]
can it run other tensorflow code?

**Comment by Nanamumuhan** [comment]
Others tensorflow  code work fine

**Comment by guotong1988** [comment]
Try python3.6?

**Comment by Nanamumuhan** [comment]
let me try it

**Comment by Nanamumuhan** [comment]
![image](https://user-images.githubusercontent.com/41236260/183331757-ec62862c-85ef-4c1f-8c84-660b9d11ccbb.png)
![image](https://user-images.githubusercontent.com/41236260/183331792-6cfc580b-1f08-42d4-9446-187d5271e586.png)
still dosen`t work

**Comment by guotong1988** [comment]
try smaller batch_size and TF=1.15?

**Comment by Nanamumuhan** [comment]
batch size =1 still not work , try TF =1.15 later

**Comment by Nanamumuhan** [comment]
![image](https://user-images.githubusercontent.com/41236260/186042807-01e1a168-829a-498d-9025-b4c3f833bb75.png)
it work ,when i use TF ＝ 1.15. thanks a lot.
